spring.application.name=intellimarket-api

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Spring Security & JWT
intellimarket.security.jwt.secret=UnaClaveSuperSecretaYMuyLargaDeIntelliMarketQueNadieDebeSaber123!
intellimarket.security.jwt.expiration-ms=900000
intellimarket.security.jwt.refresh-expiration-ms=604800000

# 🛠️ CONEXIÓN CON OLLAMA CLOUD (Datos de tu compañero)
spring.ai.openai.base-url=https://ollama.com
spring.ai.openai.api-key=69357a76dbe94ebfb1d962510c2f6201._hu3zexkDxk-pdxbwETWWBUW
spring.ai.openai.chat.options.model=gpt-oss:120b


# Server Configuration
server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Docker Compose Configuration
spring.docker.compose.enabled=false

# CORS Configuration
intellimarket.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

springdoc.override-with-generic-response=false

logging.level.org.springframework.web=DEBUG

spring.main.allow-bean-definition-overriding=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE